spring:
  application:
    name: sequence
  datasource:
    url: jdbc:mariadb://localhost:3306/sequence?useUnicode=true&characterEncoding=utf8mb4
    username: seq
    password: seq
    driver-class-name: org.mariadb.jdbc.Driver
