spring:
  application:
    name: mariadb
  datasource:

    url: jdbc:mariadb://localhost:3307/users?useUnicode=true&characterEncoding=utf8mb4
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      use-new-id-generate-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

# JWT 비밀 키
JWT_SECRET_KEY: ${JWT_SECRET_KEY}