spring:
  application:
    name: project-service

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  datasource:
    url: jdbc:mariadb://localhost:3310/project
    username: sequence
    password: sequence
    driver-class-name: org.mariadb.jdbc.Driver

  jwt:
    secret: Adsfvabewryethadbgnq4ertjadfhjmetDHJarkmyshfzdjykmrtejkymhndgThJymhfngbfc
